create database if not exists limited;
use limited;


DROP TABLE IF EXISTS M_EXCEPTION_LOG; 
DROP TABLE IF EXISTS M_ORGANIZATION;
DROP TABLE IF EXISTS M_ROLE_PERMISSION;								
DROP TABLE IF EXISTS M_USER_ROLE;
DROP TABLE IF EXISTS M_PERMISSION;
DROP TABLE IF EXISTS M_ROLE;
DROP TABLE IF EXISTS M_USER;

CREATE TABLE M_EXCEPTION_LOG
		(
			ID BIGINT(20) NOT NULL PRIMARY KEY AUTO_INCREMENT,
			TYPE VARCHAR(255),
	 		PAGE_ID VARCHAR(255),
	 		PAGE_NAME VARCHAR(255),
			LONG_METHOD VARCHAR(400),
	 		LONG_EXCEPTION TEXT,
	 		CLAZZ VARCHAR(300),
			METHOD VARCHAR(255),
	 		PARAM_TYPES VARCHAR(500),
	 		PARAMS TEXT,
	 		EXCEPTION TEXT,
			DETAIL_EXCEPTION BLOB,
	 		EXTEND_PROP1 VARCHAR(255),
			EXTEND_PROP2 VARCHAR(255),
			CREATOR_ID BIGINT(20),
	 		CREATOR VARCHAR(255),
			CREATED_TIME DATETIME,
			LAST_OPERATOR_ID BIGINT(20),
	 		LAST_OPERATOR VARCHAR(255),
			LAST_OPERATED_TIME DATETIME
		)ENGINE=INNODB  DEFAULT CHARSET=UTF8 DEFAULT COLLATE=UTF8_BIN;
		
CREATE TABLE M_ORGANIZATION
			(
				ID BIGINT(20) NOT NULL PRIMARY KEY AUTO_INCREMENT,
		 		CODE VARCHAR(255) NOT NULL UNIQUE,
		 		NAME VARCHAR(255),
				TYPE VARCHAR(255),
		 		PARENT_ORG_ID BIGINT(20),
				MANAGER VARCHAR(255),
		 		DESCRIPTION VARCHAR(255),
		 		STATUS VARCHAR(255),
		 		ENABLED BOOLEAN DEFAULT 0,
				EXTEND_PROP1 VARCHAR(255),
		 		EXTEND_PROP2 VARCHAR(255),
				CONTACT_IDENTITY_NO VARCHAR(255),
		 		CONTACT_BIRTH_DATE DATE,
		 		CONTACT_SEX VARCHAR(255),
				CONTACT_ADDRESS VARCHAR(500),
		 		CONTACT_TEL VARCHAR(255),
		 		CONTACT_MOBILE VARCHAR(255),
				CONTACT_EMAIL VARCHAR(255),
		 		CONTACT_QQ VARCHAR(255),
				CREATOR_ID BIGINT(20),
		 		CREATOR VARCHAR(255),
				CREATED_TIME DATETIME,
				LAST_OPERATOR_ID BIGINT(20),
		 		LAST_OPERATOR VARCHAR(255),
				LAST_OPERATED_TIME DATETIME
			)ENGINE=INNODB  DEFAULT CHARSET=UTF8 DEFAULT COLLATE=UTF8_BIN;
			 
			
CREATE TABLE M_USER
			(
				ID BIGINT(20) NOT NULL PRIMARY KEY AUTO_INCREMENT,
				CODE VARCHAR(255) NOT NULL UNIQUE,
				NAME VARCHAR(255),
				PASSWORD VARCHAR(255), 
				LAST_PWD VARCHAR(255),
				LAST_MD_PWD_TIME DATETIME,
				EXPIRED_DATE DATETIME,
				PASSWORD_EXPIRED_DATE DATETIME,
				LOCALE VARCHAR(255),
				BE_ROOT BOOLEAN DEFAULT 0,
				ENABLED BOOLEAN DEFAULT 0,
				CONTACT_IDENTITY_NO VARCHAR(255),
				CONTACT_BIRTH_DATE DATE,
				CONTACT_SEX VARCHAR(255),
				CONTACT_ADDRESS VARCHAR(500),
				CONTACT_TEL VARCHAR(255),
				CONTACT_MOBILE VARCHAR(255),
				CONTACT_EMAIL VARCHAR(255),
				CONTACT_QQ VARCHAR(255), 
				CREATOR_ID BIGINT(20),
				CREATOR VARCHAR(255),
				CREATED_TIME DATETIME,
				LAST_OPERATOR_ID BIGINT(20),
				LAST_OPERATOR VARCHAR(255),
				LAST_OPERATED_TIME DATETIME
			)ENGINE=INNODB  DEFAULT CHARSET=UTF8 DEFAULT COLLATE=UTF8_BIN;
			
			
CREATE TABLE M_ROLE
			(
				ID BIGINT(20) NOT NULL PRIMARY KEY AUTO_INCREMENT,
				CODE VARCHAR(255) NOT NULL UNIQUE,
				NAME VARCHAR(255),
				DESCRIPTION VARCHAR(255),
				STATUS VARCHAR(255),
				ENABLED BOOLEAN DEFAULT 0,
				EXTEND_PROP1 VARCHAR(255),
		 		EXTEND_PROP2 VARCHAR(255),
				CREATOR_ID BIGINT(20),
			 	CREATOR VARCHAR(255),
				CREATED_TIME DATETIME,
				LAST_OPERATOR_ID BIGINT(20),
		 		LAST_OPERATOR VARCHAR(255),
				LAST_OPERATED_TIME DATETIME
			)ENGINE=INNODB  DEFAULT CHARSET=UTF8 DEFAULT COLLATE=UTF8_BIN;

CREATE TABLE M_PERMISSION
		(
			ID BIGINT(20) NOT NULL PRIMARY KEY AUTO_INCREMENT,
	 		CODE VARCHAR(255) NOT NULL UNIQUE,
	 		NAME VARCHAR(255),
	 		PARENT_PERMISSION_ID BIGINT(20),
			TYPE VARCHAR(255),
	 		URL VARCHAR(500),
	 		CONTENT VARCHAR(500),
	 		BE_TOP BOOLEAN,
	 		PRIORITY INTEGER,
			DESCRIPTION VARCHAR(255),
	 		ENABLED BOOLEAN DEFAULT 0,
			CREATOR_ID BIGINT(20),
	 		CREATOR VARCHAR(255),
			CREATED_TIME DATETIME,
			LAST_OPERATOR_ID BIGINT(20),
	 		LAST_OPERATOR VARCHAR(255),
			LAST_OPERATED_TIME DATETIME,
			INDEX PARENT_PERMISSION_ID_IDX(PARENT_PERMISSION_ID)
		)ENGINE=INNODB  DEFAULT CHARSET=UTF8 DEFAULT COLLATE=UTF8_BIN;
		
		
CREATE TABLE M_USER_ROLE
			(
				ID BIGINT(20) NOT NULL PRIMARY	KEY AUTO_INCREMENT,
				USER_ID BIGINT(20),
				ROLE_ID BIGINT(20),
				ENABLED BOOLEAN DEFAULT 0,
				CREATOR_ID BIGINT(20),
				CREATOR VARCHAR(255),
				CREATED_TIME DATETIME,
				LAST_OPERATOR_ID BIGINT(20),
				LAST_OPERATOR VARCHAR(255),
				LAST_OPERATED_TIME DATETIME,
				FOREIGN KEY (USER_ID) REFERENCES M_USER(ID),
				FOREIGN KEY (ROLE_ID) REFERENCES M_ROLE(ID),
				INDEX USER_ID_INDEX(USER_ID),
				INDEX ROLE_ID_INDEX(ROLE_ID)
			)ENGINE=INNODB  DEFAULT CHARSET=UTF8 DEFAULT COLLATE=UTF8_BIN;
			
CREATE TABLE M_ROLE_PERMISSION
			(
				ID BIGINT(20) NOT NULL PRIMARY KEY AUTO_INCREMENT,
				ROLE_ID BIGINT(20),
		 		PERMISSION_ID BIGINT(20),
		 		ENABLED BOOLEAN DEFAULT 0,
				CREATOR_ID BIGINT(20),
		 		CREATOR VARCHAR(255),
				CREATED_TIME DATETIME,
				LAST_OPERATOR_ID BIGINT(20),
			 	LAST_OPERATOR VARCHAR(255),
				LAST_OPERATED_TIME DATETIME,
				FOREIGN KEY (PERMISSION_ID) REFERENCES M_PERMISSION(ID),
				FOREIGN KEY (ROLE_ID) REFERENCES M_ROLE(ID),
				INDEX PERMISSION_ID_INDEX(PERMISSION_ID),
				INDEX ROLE_ID_INDEX(ROLE_ID)
			)ENGINE=INNODB  DEFAULT CHARSET=UTF8 DEFAULT COLLATE=UTF8_BIN;
			
